import type { Metadata } from 'next'
import './globals.css'

export const metadata: Metadata = {
  title: 'Quvi app',
  description: 'Generated by Jonathan de la Sen'
}

export default function RootLayout ({
  children
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="en">
      <body >{children}</body>
    </html>
  )
}
